// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsK-0SYvOq6Vvkc9ZgBiTDqdo81mQZmbE',
    appId: '1:977057517893:web:690a60d37ea18541b0ae2c',
    messagingSenderId: '977057517893',
    projectId: 'facebook2-258ba',
    authDomain: 'facebook2-258ba.firebaseapp.com',
    storageBucket: 'facebook2-258ba.appspot.com',
    measurementId: 'G-KM8P1J13DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvlwz9fQLat7Ks9DOSUYayt9DkRI21XiA',
    appId: '1:977057517893:android:f422ee8cf338d30db0ae2c',
    messagingSenderId: '977057517893',
    projectId: 'facebook2-258ba',
    storageBucket: 'facebook2-258ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJfnRYzcXqUvBc4CVA1mZtRGOGOF-Bf7w',
    appId: '1:977057517893:ios:ccef4f14af49c5aeb0ae2c',
    messagingSenderId: '977057517893',
    projectId: 'facebook2-258ba',
    storageBucket: 'facebook2-258ba.appspot.com',
    iosClientId: '977057517893-pu9ctithlvpf017udaono864burfr6lh.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebook',
  );
}
